#!/usr/bin/env python3
"""Generate three-turn experiment configs and submission script.

Experiments from PLAN.md + pareto frontier analysis:
  # Original plan (turn3 = 14t)
  4nt  -> 1.7t -> 14t
  4nt  -> 4t   -> 14t
  4nt  -> 8t   -> 14t
  8nt  -> 1.7t -> 14t
  14nt -> 4t   -> 14t
  14nt -> 8t   -> 14t
  # All-nothink cascades (push low-latency frontier)
  4nt  -> 8nt  -> 14nt
  1.7nt -> 4nt -> 14nt
  # 8nt turn1 with think escalation
  8nt  -> 4t   -> 14t
  8nt  -> 8t   -> 14t
  # Non-14t turn3 (cheaper escalation, 95-97% band)
  4nt  -> 1.7t -> 8t
  8nt  -> 1.7t -> 8t
"""

from pathlib import Path

import yaml

# Model specs: short_name -> (hf_name, think)
MODELS = {
    "0.6nt": ("Qwen/Qwen3-0.6B", False),
    "0.6t": ("Qwen/Qwen3-0.6B", True),
    "1.7nt": ("Qwen/Qwen3-1.7B", False),
    "1.7t": ("Qwen/Qwen3-1.7B", True),
    "4nt": ("Qwen/Qwen3-4B", False),
    "4t": ("Qwen/Qwen3-4B", True),
    "8nt": ("Qwen/Qwen3-8B", False),
    "8t": ("Qwen/Qwen3-8B", True),
    "14nt": ("Qwen/Qwen3-14B", False),
    "14t": ("Qwen/Qwen3-14B", True),
}

EXPERIMENTS = [
    # Original plan (turn3 = 14t)
    ("4nt", "1.7t", "14t"),
    ("4nt", "4t", "14t"),
    ("4nt", "8t", "14t"),
    ("8nt", "1.7t", "14t"),
    ("14nt", "4t", "14t"),
    ("14nt", "8t", "14t"),
    # All-nothink cascades (push low-latency frontier)
    ("4nt", "8nt", "14nt"),
    ("1.7nt", "4nt", "14nt"),
    # 8nt turn1 with think escalation
    ("8nt", "4t", "14t"),
    ("8nt", "8t", "14t"),
    # Non-14t turn3 (cheaper escalation, 95-97% band)
    ("4nt", "1.7t", "8t"),
    ("8nt", "1.7t", "8t"),
    # Compositional substitution from 1T/2T dominance analysis
    # 4nt→8nt dominates 8nt/14nt as turn 1 (mean latency)
    ("4nt", "8nt", "1.7t"),
    ("4nt", "8nt", "4t"),
    ("4nt", "8nt", "8t"),
    ("4nt", "8nt", "14t"),
    # 1.7nt→4nt dominates 8nt as turn 1 (P90-optimal, tighter tail)
    ("1.7nt", "4nt", "4t"),
    # Turn 2 substitution: 14t → 14nt→4t
    ("4nt", "14nt", "4t"),
]

BASE_PORT = 31100  # Use a distinct port range to avoid collisions with two-turn


def size_label(short_name: str) -> str:
    """Extract size for benchmark name, e.g. '4nt' -> '4b', '1.7t' -> '1.7b'."""
    return short_name.replace("nt", "b").replace("t", "b")


def generate_config(turn1: str, turn2: str, turn3: str, port_base: int) -> dict:
    hf1, think1 = MODELS[turn1]
    hf2, think2 = MODELS[turn2]
    hf3, think3 = MODELS[turn3]

    ports = [port_base, port_base + 1, port_base + 2]

    # Deduplicate servers sharing the same (model, think) — reuse the same port
    server_specs = []
    port_map = {}
    seen = {}
    for i, (hf, think, turn_key) in enumerate(
        [
            (hf1, think1, "model_config_turn1"),
            (hf2, think2, "model_config_turn2"),
            (hf3, think3, "model_config_turn3"),
        ]
    ):
        key = (hf, think)
        if key in seen:
            port_map[turn_key] = seen[key]
        else:
            port = ports[len(server_specs)]
            device = len(server_specs)
            seen[key] = port
            port_map[turn_key] = port
            server_specs.append(
                {
                    "model": hf,
                    "port": port,
                    "tp": 1,
                    "mem_fraction": 0.95,
                    "device": device,
                    "extra_body": {
                        "chat_template_kwargs": {"enable_thinking": think}
                    },
                }
            )

    name = f"humaneval_threeturn_{size_label(turn1)}_{size_label(turn2)}_{size_label(turn3)}"

    config = {
        "servers": server_specs,
        "benchmarks": [
            {
                "name": name,
                "scenario_file": "benchmarks/HumanEval/Tasks/human_eval_AgentChatCopyNoCtx.jsonl",
                "server_port": server_specs[0]["port"],
                "config_template": "scripts/configs/config-threeturn-template.yaml",
                "server_port_map": port_map,
                "repeat": 3,
            }
        ],
        "server_startup_timeout": 600,
        "server_health_check_interval": 5,
        "shutdown_timeout": 30,
    }
    return config


def main():
    configs_dir = Path(__file__).resolve().parent.parent / "configs"
    study_dir = Path(__file__).resolve().parent

    submit_lines = [
        "#!/bin/bash",
        "# Submit all three-turn experiment runs",
        f"# Total runs: {len(EXPERIMENTS)}",
        "# Generated by generate_configs.py",
        "",
        "set -e",
        "",
    ]

    for i, (t1, t2, t3) in enumerate(EXPERIMENTS):
        port_base = BASE_PORT + i * 3
        config = generate_config(t1, t2, t3, port_base)

        slug = f"{t1}-{t2}-{t3}"
        config_path = configs_dir / f"config-threeturn-nc-{slug}.yaml"
        output_dir = f"outputs/three-turn-nc-{slug}"

        # Determine GPU count needed (number of unique servers)
        num_gpus = len(config["servers"])

        with open(config_path, "w") as f:
            f.write(f"# Three-turn benchmark configuration\n")
            f.write(f"# Turn 1: {t1} (port {config['servers'][0]['port']})\n")
            if len(config["servers"]) > 1:
                f.write(
                    f"# Turn 2: {t2} (port {config['benchmarks'][0]['server_port_map']['model_config_turn2']})\n"
                )
            else:
                f.write(f"# Turn 2: {t2} (reuses turn 1 server)\n")
            f.write(
                f"# Turn 3: {t3} (port {config['benchmarks'][0]['server_port_map']['model_config_turn3']})\n"
            )
            f.write("\n")
            yaml.dump(config, f, default_flow_style=False, sort_keys=False)

        print(f"  Generated: {config_path.name}  ({num_gpus} GPUs)")

        submit_lines.append(f'echo "[{i+1}/{len(EXPERIMENTS)}] Submitting {t1} -> {t2} -> {t3} ({num_gpus} GPUs)"')
        submit_lines.append(
            f'sbatch scripts/three_turn_study/start_threeturn.sh '
            f'"scripts/configs/config-threeturn-nc-{slug}.yaml" '
            f'"{output_dir}"'
        )

    submit_lines.append("")
    submit_lines.append(f'echo "All {len(EXPERIMENTS)} three-turn jobs submitted."')

    submit_path = study_dir / "submit_threeturn.sh"
    with open(submit_path, "w") as f:
        f.write("\n".join(submit_lines) + "\n")
    submit_path.chmod(0o755)
    print(f"\n  Generated: {submit_path.name}")


if __name__ == "__main__":
    main()
