#!/usr/bin/env python3
"""Generate four-turn experiment configs derived from 2-turn frontier substitution.

Strategy: replace one model in a 2-turn Pareto-optimal config with a 3-turn cascade
that dominates it, creating a 4-turn config.

Dominance relationships used:
  0.6nt-1.7nt-4nt (85.77%, 3.57s) dominates 8nt (82.11%, 5.53s) and 1.7t (84.55%, 15.31s)
  4nt-8nt-14nt   (94.72%, 6.70s) dominates 14nt (90.12%, 9.63s) [used in v1 runs]
  4nt-8nt-1.7t   (93.29%, 8.50s) dominates 14nt (90.12%, 9.63s) [introduces thinking]
  1.7nt-4nt-14nt (94.72%, 9.75s) dominates 4t   (93.70%, 29.44s)
  1.7nt-4nt-4t   (95.33%, 14.88s) dominates 4t  (93.70%, 29.44s)
"""

from pathlib import Path

import yaml

# Model specs: short_name -> (hf_name, think)
MODELS = {
    "0.6nt": ("Qwen/Qwen3-0.6B", False),
    "0.6t": ("Qwen/Qwen3-0.6B", True),
    "1.7nt": ("Qwen/Qwen3-1.7B", False),
    "1.7t": ("Qwen/Qwen3-1.7B", True),
    "4nt": ("Qwen/Qwen3-4B", False),
    "4t": ("Qwen/Qwen3-4B", True),
    "8nt": ("Qwen/Qwen3-8B", False),
    "8t": ("Qwen/Qwen3-8B", True),
    "14nt": ("Qwen/Qwen3-14B", False),
    "14t": ("Qwen/Qwen3-14B", True),
}

EXPERIMENTS = [
    # === Group A: Replace T1=8nt with 0.6nt-1.7nt-4nt cascade ===
    # (cascade dominates 8nt as 1-turn: 85.77% vs 82.11%, 3.57s vs 5.53s)

    # From 2T 8nt-4t (96.65%, 14.32s)
    ("0.6nt", "1.7nt", "4nt", "4t"),

    # === Group B: Replace T1=14nt with 4nt-8nt-1.7t cascade ===
    # (4nt-8nt-1.7t at 93.29%, 8.5s dominates 14nt at 90.12%, 9.63s)
    # Introduces thinking mode transition — different from all-nothink cascade

    # From 2T 14nt-4t (96.95%, 17.37s)
    ("4nt", "8nt", "1.7t", "4t"),
    # From 2T 14nt-14t (97.56%, 25.21s)
    ("4nt", "8nt", "1.7t", "14t"),

    # === Group C: Extend strong 3T cascades with rescue turn ===
    # 1.7nt-4nt-14nt (94.72%, 9.75s) — strong all-nothink staircase + heavy rescue
    ("1.7nt", "4nt", "14nt", "14t"),
    # 1.7nt-4nt-4t (95.33%, 14.88s) — nothink start, think escalation + heavy rescue
    ("1.7nt", "4nt", "4t", "14t"),
]

BASE_PORT = 31300  # Distinct port range to avoid collisions with v1 runs


def size_label(short_name: str) -> str:
    """Extract size for benchmark name, e.g. '4nt' -> '4b', '1.7t' -> '1.7b'."""
    return short_name.replace("nt", "b").replace("t", "b")


def generate_config(turns: tuple[str, ...], port_base: int) -> dict:
    turn_specs = [(MODELS[t][0], MODELS[t][1]) for t in turns]

    # Deduplicate servers sharing the same (model, think) — reuse the same port
    server_specs = []
    port_map = {}
    seen = {}
    for i, (hf, think) in enumerate(turn_specs):
        turn_key = f"model_config_turn{i + 1}"
        key = (hf, think)
        if key in seen:
            port_map[turn_key] = seen[key]
        else:
            port = port_base + len(server_specs)
            device = len(server_specs)
            seen[key] = port
            port_map[turn_key] = port
            server_specs.append(
                {
                    "model": hf,
                    "port": port,
                    "tp": 1,
                    "mem_fraction": 0.95,
                    "device": device,
                    "extra_body": {
                        "chat_template_kwargs": {"enable_thinking": think}
                    },
                }
            )

    name = "humaneval_fourturn_" + "_".join(size_label(t) for t in turns)

    config = {
        "servers": server_specs,
        "benchmarks": [
            {
                "name": name,
                "scenario_file": "benchmarks/HumanEval/Tasks/human_eval_AgentChatCopyNoCtx.jsonl",
                "server_port": server_specs[0]["port"],
                "config_template": "scripts/configs/config-fourturn-template.yaml",
                "server_port_map": port_map,
                "repeat": 3,
            }
        ],
        "server_startup_timeout": 600,
        "server_health_check_interval": 5,
        "shutdown_timeout": 30,
    }
    return config


def main():
    configs_dir = Path(__file__).resolve().parent.parent / "configs"
    study_dir = Path(__file__).resolve().parent

    submit_lines = [
        "#!/bin/bash",
        "# Submit four-turn v2 experiments (2T frontier substitution)",
        f"# Total runs: {len(EXPERIMENTS)}",
        "# Generated by generate_configs_v2.py",
        "",
        "set -e",
        "",
    ]

    for i, turns in enumerate(EXPERIMENTS):
        port_base = BASE_PORT + i * 4
        config = generate_config(turns, port_base)

        slug = "-".join(turns)
        config_path = configs_dir / f"config-fourturn-nc-{slug}.yaml"
        output_dir = f"outputs/four-turn-nc-{slug}"

        num_gpus = len(config["servers"])

        with open(config_path, "w") as f:
            f.write("# Four-turn benchmark configuration (v2 — frontier substitution)\n")
            for j, t in enumerate(turns):
                port = config["benchmarks"][0]["server_port_map"][f"model_config_turn{j+1}"]
                f.write(f"# Turn {j+1}: {t} (port {port})\n")
            f.write("\n")
            yaml.dump(config, f, default_flow_style=False, sort_keys=False)

        print(f"  Generated: {config_path.name}  ({num_gpus} GPUs)")

        submit_lines.append(
            f'echo "[{i+1}/{len(EXPERIMENTS)}] Submitting {" -> ".join(turns)} ({num_gpus} GPUs)"'
        )
        submit_lines.append(
            f'sbatch --gres=gpu:nvidia_rtx_6000_ada_generation:{num_gpus} '
            f'scripts/four_turn_study/start_fourturn.sh '
            f'"scripts/configs/config-fourturn-nc-{slug}.yaml" '
            f'"{output_dir}"'
        )
        submit_lines.append("")

    submit_lines.append(f'echo "All {len(EXPERIMENTS)} four-turn v2 jobs submitted."')

    submit_path = study_dir / "submit_fourturn_v2.sh"
    with open(submit_path, "w") as f:
        f.write("\n".join(submit_lines) + "\n")
    submit_path.chmod(0o755)
    print(f"\n  Generated: {submit_path.name}")


if __name__ == "__main__":
    main()
