#!/usr/bin/env python3
"""Generate four-turn experiment configs and submission script.

Strategy: extend the best 3T Pareto frontier configs with a heavy turn-4 model.
Primary target: 4nt -> 8nt -> 4t -> 14t (fast 3T base + 14B-think rescue)
"""

from pathlib import Path

import yaml

# Model specs: short_name -> (hf_name, think)
MODELS = {
    "0.6nt": ("Qwen/Qwen3-0.6B", False),
    "0.6t": ("Qwen/Qwen3-0.6B", True),
    "1.7nt": ("Qwen/Qwen3-1.7B", False),
    "1.7t": ("Qwen/Qwen3-1.7B", True),
    "4nt": ("Qwen/Qwen3-4B", False),
    "4t": ("Qwen/Qwen3-4B", True),
    "8nt": ("Qwen/Qwen3-8B", False),
    "8t": ("Qwen/Qwen3-8B", True),
    "14nt": ("Qwen/Qwen3-14B", False),
    "14t": ("Qwen/Qwen3-14B", True),
}

EXPERIMENTS = [
    # Primary: fast 3T base (96.8%, P90=15.4s) + heavy rescue
    ("4nt", "8nt", "4t", "14t"),
    # Variant: nothink turn3 + heavy rescue (compare 4t vs 14nt as T3)
    ("4nt", "8nt", "14nt", "14t"),
    # Skip 8nt, escalate to 14nt earlier, then think models
    ("4nt", "14nt", "4t", "14t"),
    # All-nothink first 3 turns, cheap think rescue at T4
    ("4nt", "8nt", "14nt", "4t"),
]

BASE_PORT = 31200  # Distinct port range to avoid collisions


def size_label(short_name: str) -> str:
    """Extract size for benchmark name, e.g. '4nt' -> '4b', '1.7t' -> '1.7b'."""
    return short_name.replace("nt", "b").replace("t", "b")


def generate_config(turns: tuple[str, ...], port_base: int) -> dict:
    turn_specs = [(MODELS[t][0], MODELS[t][1]) for t in turns]

    # Deduplicate servers sharing the same (model, think) — reuse the same port
    server_specs = []
    port_map = {}
    seen = {}
    for i, (hf, think) in enumerate(turn_specs):
        turn_key = f"model_config_turn{i + 1}"
        key = (hf, think)
        if key in seen:
            port_map[turn_key] = seen[key]
        else:
            port = port_base + len(server_specs)
            device = len(server_specs)
            seen[key] = port
            port_map[turn_key] = port
            server_specs.append(
                {
                    "model": hf,
                    "port": port,
                    "tp": 1,
                    "mem_fraction": 0.95,
                    "device": device,
                    "extra_body": {
                        "chat_template_kwargs": {"enable_thinking": think}
                    },
                }
            )

    name = "humaneval_fourturn_" + "_".join(size_label(t) for t in turns)

    config = {
        "servers": server_specs,
        "benchmarks": [
            {
                "name": name,
                "scenario_file": "benchmarks/HumanEval/Tasks/human_eval_AgentChatCopyNoCtx.jsonl",
                "server_port": server_specs[0]["port"],
                "config_template": "scripts/configs/config-fourturn-template.yaml",
                "server_port_map": port_map,
                "repeat": 3,
            }
        ],
        "server_startup_timeout": 600,
        "server_health_check_interval": 5,
        "shutdown_timeout": 30,
    }
    return config


def main():
    configs_dir = Path(__file__).resolve().parent.parent / "configs"
    study_dir = Path(__file__).resolve().parent

    submit_lines = [
        "#!/bin/bash",
        "# Submit all four-turn experiment runs",
        f"# Total runs: {len(EXPERIMENTS)}",
        "# Generated by generate_configs.py",
        "",
        "set -e",
        "",
    ]

    for i, turns in enumerate(EXPERIMENTS):
        port_base = BASE_PORT + i * 4
        config = generate_config(turns, port_base)

        slug = "-".join(turns)
        config_path = configs_dir / f"config-fourturn-nc-{slug}.yaml"
        output_dir = f"outputs/four-turn-nc-{slug}"

        num_gpus = len(config["servers"])

        with open(config_path, "w") as f:
            f.write("# Four-turn benchmark configuration\n")
            for j, t in enumerate(turns):
                port = config["benchmarks"][0]["server_port_map"][f"model_config_turn{j+1}"]
                f.write(f"# Turn {j+1}: {t} (port {port})\n")
            f.write("\n")
            yaml.dump(config, f, default_flow_style=False, sort_keys=False)

        print(f"  Generated: {config_path.name}  ({num_gpus} GPUs)")

        submit_lines.append(
            f'echo "[{i+1}/{len(EXPERIMENTS)}] Submitting {" -> ".join(turns)} ({num_gpus} GPUs)"'
        )
        submit_lines.append(
            f'sbatch --gres=gpu:nvidia_rtx_6000_ada_generation:{num_gpus} '
            f'scripts/four_turn_study/start_fourturn.sh '
            f'"scripts/configs/config-fourturn-nc-{slug}.yaml" '
            f'"{output_dir}"'
        )

    submit_lines.append("")
    submit_lines.append(f'echo "All {len(EXPERIMENTS)} four-turn jobs submitted."')

    submit_path = study_dir / "submit_fourturn.sh"
    with open(submit_path, "w") as f:
        f.write("\n".join(submit_lines) + "\n")
    submit_path.chmod(0o755)
    print(f"\n  Generated: {submit_path.name}")


if __name__ == "__main__":
    main()
